<?php


namespace App\Html;

use App\Exceptions\FormBuilderException;
use Collective\Html\FormBuilder as CollectiveFormBuilder;
use Collective\Html\HtmlBuilder;
use Illuminate\Contracts\Routing\UrlGenerator;
use MezzoLabs\Mezzo\Cockpit\Html\Rendering\FormBuilder as CockpitFormBuilder;

class FormBuilder extends CollectiveFormBuilder
{
    /**
     * @var CockpitFormBuilder
     */
    protected $cockpitFormBuilder;

    /**
     * Create a new form builder instance.
     *
     * @param  \Illuminate\Contracts\Routing\UrlGenerator $url
     * @param  \Collective\Html\HtmlBuilder $html
     * @param  string $csrfToken
     *
     * @return void
     */
    public function __construct(HtmlBuilder $html, UrlGenerator $url, $csrfToken)
    {
        parent::__construct($html, $url, $csrfToken);

        $this->cockpitFormBuilder = app(CockpitFormBuilder::class);
    }


    public function attribute(string $name, array $options = [])
    {
        if (!$this->model) {
            throw new FormBuilderException('No model is set.');
        }

        $modelReflection = mezzo()->model(get_class($this->model));

        if (!$modelReflection->attributes()->has($name)) {
            throw new FormBuilderException("The model doesn't have an attribute called \"" . $name . "\".");
        }

        $attribute = $modelReflection->attributes($name);

        return $attribute->render($options);
    }

    /**
     * Set the model instance on the form builder.
     *
     * @param  mixed $model
     *
     * @return void
     */
    public function setModel($model)
    {
        $this->cockpitFormBuilder->setModel($model);
        parent::setModel($model);
    }

    /**
     * Create a new model based form builder.
     *
     * @param  mixed $model
     * @param  array $options
     *
     * @return string
     */
    public function model($model, array $options = [])
    {
        $this->setModel($model);
        return parent::model($model, $options);
    }

    /**
     * Open up a new HTML form.
     *
     * @param  array $options
     *
     * @return string
     */
    public function open(array $options = [])
    {
        if (isset($options['model']) && $options['model'])
            $this->setModel($options['model']);

        return parent::open($options); // TODO: Change the autogenerated stub
    }
}