<?php


namespace MezzoLabs\Mezzo\Modules\General;


use MezzoLabs\Mezzo\Core\Modularisation\Domain\ValidationRules\AlphaSpaceDashRule;
use MezzoLabs\Mezzo\Core\Modularisation\Generic\AbstractGeneralModule;
use MezzoLabs\Mezzo\Modules\General\Options\OptionFieldRegistry;

class GeneralModule extends AbstractGeneralModule
{
    protected $models = [];

    protected $group = "admin";

    protected $options = [
        'icon' => 'ion-speedometer',
        'permissions' => 'administrate'
    ];

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('mezzo.options.registry', OptionFieldRegistry::class);

    }

    /**
     * Called when module is ready, model reflections are loaded.
     *
     * @return mixed
     */
    public function ready()
    {
        $this->loadViews();

        AlphaSpaceDashRule::register();

    }


    public function generateRoutes()
    {
        parent::generateRoutes(); // TODO: Change the autogenerated stub
    }


}